app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from account import views
from product.views import user_product_list

urlpatterns = [
    # Django admin
    path('admin/', admin.site.urls),
    # ユーザ top画面
    path('', include('product.user_urls')),
    # ユーザ カート画面
    path('cart/', include('cart.user_urls')),
    # ユーザ 注文情報入力画面
    path('order/', include('order.user_urls')),

    # ログイン（スタッフ）
    path('staff/', views.staff_login, name='staff_login'),
    # ログアウト（スタッフ）
    path('staff/logout', views.staff_logout, name='staff_logout'),

    # 商品管理画面（スタッフ）
    path('staff/product/', include('product.staff_urls')),
    # カテゴリー管理画面（スタッフ）
    path('staff/category/', include('category.staff_urls')),
    # スタッフ管理画面（スタッフ）
    path('staff/account/', include('account.staff_urls')),
    # 注文情報画面（スタッフ）
    path('staff/order/', include('order.staff_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/order/forms.py
import jaconv
import re

from django import forms

from prefecture.models import Prefecture


class OrderInfoForm(forms.Form):
    """ 注文者情報入力 form """

    name = forms.CharField(
        label='お名前',
        max_length=64,
        required=True
    )
    name_kana = forms.CharField(
        label='フリガナ',
        max_length=64,
        required=True
    )
    # メールアドレス
    email_address = forms.EmailField(
        label='メールアドレス',
        max_length=64,
        required=True
    )
    phone_number = forms.CharField(
        label='電話番号',
        max_length=13,
        required=True
    )
    postal_code = forms.CharField(
        label='郵便番号',
        max_length=7,
        required=True,
    )
    prefecture = forms.ModelChoiceField(
        label='都道府県',
        queryset=Prefecture.objects.all(),
        required=True
    )
    municipality = forms.CharField(
        label='市区町村',
        max_length=128,
        required=True
    )
    address = forms.CharField(
        label='住所',
        max_length=128,
        required=True
    )

    def clean_name_kana(self):
        """ フリガナのバリデーション
        # 半角の場合全角に置換し、カナ、ハイフン、空白文字（スペース）のみで入力されているかをチェックする
        """
        name_kana = self.cleaned_data['name_kana']
        # 全角カナに置換（ascii=True 記号も全角変換の対象にする）
        zenkaku_name_kana = jaconv.h2z(name_kana, ascii=True)
        # 全角カナ、ハイフン、空白文字（スペース）で入力されているかをチェック
        # \s = 空白文字
        # ー = 全角のばし
        # - をh2zすると、－ になる
        if not re.match(r'^[ァ-ヴ][ァ-ヴー－\s]*$', zenkaku_name_kana):
            raise forms.ValidationError("カタカナとスペースのみで入力してください。")
        return zenkaku_name_kana

    def clean_phone_number(self):
        """ 電話番号のバリデーション
        # 数字のみで入力されているかをチェックする
        # ハイフンは除去する
        """
        phone_number = self.cleaned_data['phone_number']
        # 全角に置換（digit=True 数字も半角変換の対象にする、ascii=True 記号も半価格変換の対象にする）
        hankaku_phone_number = jaconv.z2h(phone_number, digit=True, ascii=True)
        # ハイフンを除去
        # － をz2hすると、ｰ になる
        replaced_phone_number = re.sub('[-ｰ]', '', hankaku_phone_number)

        if not re.match(r'^[0-9]+$', replaced_phone_number):
            raise forms.ValidationError("数字のみで入力してください。")
        return replaced_phone_number

    def clean_postal_code(self):
        """ 郵便番号のバリデーション
        # 数字のみで入力されているかをチェックする
        # ハイフンは除去する
        """
        postal_code = self.cleaned_data['postal_code']
        # 全角に置換（digit=True 数字も半角変換の対象にする、ascii=True 記号も半価格変換の対象にする）
        hankaku_phone_number = jaconv.z2h(postal_code, digit=True, ascii=True)
        # ハイフンを除去
        replaced_postal_code = re.sub('[-ｰ]', '', hankaku_phone_number)

        if not re.match(r'^[0-9]+$', replaced_postal_code):
            raise forms.ValidationError("数字のみで入力してください。")
        return replaced_postal_code


class OrderSearchForm(forms.Form):
    """ 注文情報検索フォーム（スタッフ画面） """
    created_at_from = forms.DateTimeField(
        label='注文日',
        widget=forms.DateInput(attrs={"type": "date"}),
        input_formats=['%Y-%m-%d'],
        required=False,
    )
    created_at_to = forms.DateTimeField(
        widget=forms.DateInput(attrs={"type": "date"}),
        input_formats=['%Y-%m-%d'],
        required=False,
    )

app/account/views/user.py
from django.shortcuts import render

app/cart/views/user.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from product.models import Product
from product.forms import QtyForm


def user_cart(request):
    """ ユーザカート 一覧

    :param request:
    :return:
    """
    # del request.session['cart']
    cart = request.session.get('cart')
    cart_items = []
    qty_form = QtyForm()
    total_price = 0

    # カート内商品の個数更新, 削除
    if request.method == 'POST':
        # カート内商品削除
        if 'delete-cart-item' in request.POST:
            product_id = request.POST.get('product_id')
            # カート内から同じ要素を検索して削除
            for c in cart:
                if product_id == c['product_id']:
                    cart.remove(c)

            messages.error(request, '商品を削除しました')
            request.session['cart'] = cart

        # カート内商品の個数更新
        else:
            qty_form = QtyForm(request.POST)
            if qty_form.is_valid():
                cleaned_data = qty_form.cleaned_data
                # カートに追加する商品idと数量を取得
                product_id = request.POST.get('product_id')
                qty = int(cleaned_data['qty'])
                # カート内の商品の数量を更新する
                for c in cart:
                    if c['product_id'] == product_id:
                        c['qty'] = qty
                messages.success(request, '個数を更新しました')
                # セッションのcartの情報を更新
                request.session['cart'] = cart
                return redirect('user_cart')

            else:
                messages.error(request, '個数は100以下で入力してください')

    if cart:
        for item in cart:
            product_id = item['product_id']
            qty = int(item['qty'])

            product = get_object_or_404(Product, id=product_id)
            # 数量formの追加 （商品名とかもformに含めた方がいいのかな？-> 様子み）
            initial_dict = {'qty': qty, 'product_id': product.id}
            qty_form = QtyForm(initial=initial_dict)
            product.qty_form = qty_form
            # 小計
            subtotal_price = product.price * qty
            product.subtotal = subtotal_price
            # 合計に加算
            total_price += subtotal_price
            # カートに商品を追加
            cart_items.append(product)

    return render(
        request,
        'user/user_cart.html',
        context={
            'cart_items': cart_items,
            'qty_form': qty_form,
            'total_price': total_price,
        }
    )

# TODO 削除する
# def user_cart_add(request):
#     """ ユーザカート追加
#
#     :param request:
#     :return:
#     """
#     cart = request.session.get('cart', [])
#     exist_ids = []
#     update_qty_flg = False  # カート内の数量を変更したのかを判別するフラグ
#
#     if request.method == 'POST':
#         if 'update-qty' in request.POST:
#             update_qty_flg = True
#
#         qty_form = QtyForm(request.POST)
#         if qty_form.is_valid():
#             cleaned_data = qty_form.cleaned_data
#
#             # カートに追加する商品idと数量を取得
#             product_id = request.POST.get('product_id')
#             qty = int(cleaned_data['qty'])
#
#             # セッションのcartに入れる形にセット
#             add_item = {'product_id': product_id, 'qty': qty}
#
#             # 商品詳細画面からカートに追加
#             if not update_qty_flg:
#                 # セッションのカートに何かしら入っている場合は、同じ商品idがあるかチェック
#                 if cart:
#                     # 既にセッションに入っている商品idリスト
#                     for c in cart:
#                         exist_ids.append(c['product_id'])
#
#                     # セッションに商品idが存在するかをみる
#                     exist_flag = False
#                     for item in cart:
#                         # 追加する商品idがセッション内に存在したら、数量のみ加算する
#                         if product_id in exist_ids:
#                             if item['product_id'] == product_id:
#                                 item['qty'] += qty
#                                 exist_flag = True
#                     # memo => 「if item['product_id'] == product_id:」のelseでappendすると無限ループになる
#                     if not exist_flag:
#                         cart.append(add_item)
#
#                 # なければカートに追加
#                 else:
#                     cart.append(add_item)
#                 messages.success(request, 'カートに追加しました')
#
#             else:
#                 # カート内の商品の数量を更新する
#                 for c in cart:
#                     if c['product_id'] == product_id:
#                         c['qty'] = add_item['qty']
#                 messages.success(request, '個数を更新しました')
#
#             # セッションのcartの情報を更新
#             request.session['cart'] = cart
#
#             return redirect('user_cart')

app/order/views/user.py
from django.shortcuts import render, get_object_or_404

from core.utils import send_mail, calc_price_tax
from order.forms import OrderInfoForm
from order.models import Sales, SalesDetails
from prefecture.models import Prefecture
from product.models import Product


# TODO required＿postにする
def user_order(request):
    """ 注文情報入力

    :param request:
    :return:
    """
    if request.method == 'POST':
        # 注文者情報入力
        if 'input-order-info' in request.POST:
            form = OrderInfoForm()

            return render(
                request,
                'user/user_input_order_info.html',
                context={
                    'form': form,
                }
            )

        # 注文者情報確認
        if 'confirm-order-info' in request.POST:
            form = OrderInfoForm(request.POST)
            if form.is_valid():
                clean_prefecture = form.cleaned_data['prefecture']
                # 画面表示用の都道府県
                prefecture = Prefecture.objects.get(id=clean_prefecture.id)
                return render(
                    request,
                    'user/user_confirm_order_info.html',
                    context={
                        'form': form,
                        'prefecture': prefecture
                    }
                )
            else:
                return render(
                    request,
                    'user/user_input_order_info.html',
                    context={
                        'form': form,
                    }
                )


# TODO required＿postにする
def user_order_done(request):

    cart = request.session['cart']
    display_order_items = []
    total_price = 0

    # メールの本文に表示する、注文商品情報をまとめる
    for item in cart:
        product_id = item['product_id']
        qty = int(item['qty'])
        product = get_object_or_404(Product, id=product_id)
        # 各商品の小計
        subtotal_price = product.price * qty
        item_dict = {
            'product_name': product.name,
            'price': product.price,
            'qty': qty,
            'subtotal_price': subtotal_price,
        }
        display_order_items.append(item_dict)
        # 合計金額（税抜き）
        total_price += subtotal_price
    # 合計金額（税込み）
    calc_total_price = calc_price_tax(total_price)

    # メールの本文に表示する注文者情報
    prefecture = Prefecture.objects.get(id=request.POST['prefecture'])
    name = request.POST['name']
    name_kana = request.POST['name_kana']
    email_address = request.POST['email_address']
    phone_number = request.POST['phone_number']
    postal_code = request.POST['postal_code']
    address = prefecture.prefecture_name + request.POST['municipality'] + request.POST['address']

    context = {
        'name': name,
        'phone_number': phone_number,
        'postal_code': postal_code,
        'address': address,
        'display_order_items': display_order_items,
        'total_price': total_price,  # 税抜き合計
        'calc_total_price': calc_total_price,  # 税込み合計
    }
    to_list = [email_address]

    send_mail_result = send_mail(
        request,
        '【d_shopping】ご注文ありがとうございます。',
        'email_txt/user_order_done_email.txt',
        context,
        to_list,
    )
    sales = Sales.objects.create(
        name=name,
        name_kana=name_kana,
        email_address=email_address,
        phone_number=phone_number,
        postal_code=postal_code,
        prefecture=prefecture,
        municipality=request.POST['municipality'],
        address=request.POST['address'],
        member_code=0
    )
    for item in cart:
        product_id = item['product_id']
        qty = int(item['qty'])
        product = get_object_or_404(Product, id=product_id)

        sales_details = SalesDetails.objects.create(
            sales=sales,
            product_id=product.pk,
            price=product.price,
            quantity=qty
        )

    # セッションのカート情報をクリア
    del request.session['cart']

    return render(
        request,
        'user/user_order_done.html',
        context={
            'name': name,
            'email_address': email_address,
        }
    )

app/product/views/user.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.contrib import messages

from product.forms import QtyForm
from product.models import Product


def user_product_list(request):
    """ 商品一覧（ユーザトップ画面）

    :param request:
    :return:
    """

    qs = Product.objects.filter(is_published=1, is_deleted=False)
    page_obj = qs.order_by('-created_at')

    return render(
        request,
        'user/user_product_list.html',
        context={
            'page_obj': page_obj,

        }
    )


def user_product_details(request, product_id):
    """ 商品詳細画面（ユーザ）

    :param request:
    :return:
    """
    product = get_object_or_404(Product, id=product_id)

    # 初期表示
    if request.method == 'GET':
        initial_dict = {'qty': 1, 'product_id': product.id}
        qty_form = QtyForm(initial=initial_dict)

    # 商品をカートへ追加
    else:
        cart = request.session.get('cart', [])
        exist_ids = []
        qty_form = QtyForm(request.POST)
        if qty_form.is_valid():
            cleaned_data = qty_form.cleaned_data

            # カートに追加する商品idと数量を取得
            product_id = request.POST.get('product_id')
            qty = int(cleaned_data['qty'])

            # セッションのcartに入れる形にセット
            add_item = {'product_id': product_id, 'qty': qty}

            # セッションのカートに何かしら入っている場合は、同じ商品idがあるかチェック
            if cart:
                # 既にセッションに入っている商品idリスト
                for c in cart:
                    exist_ids.append(c['product_id'])

                # セッションに商品idが存在するかをみる
                exist_flag = False
                for item in cart:
                    # 追加する商品idがセッション内に存在したら、数量のみ加算する
                    if product_id in exist_ids:
                        if item['product_id'] == product_id:
                            item['qty'] += qty
                            exist_flag = True
                # memo => 「if item['product_id'] == product_id:」のelseでappendすると無限ループになる
                if not exist_flag:
                    cart.append(add_item)

            # なければカートに追加
            else:
                cart.append(add_item)

            request.session['cart'] = cart
            messages.success(request, 'カートに追加しました')
            return redirect('user_cart')

    return render(
        request,
        'user/user_product_details.html',
        context={
            'form': qty_form,
            'product': product,
        }
    )

app/templates/user/user_cart.html
{% extends "load_file.html" %}
{% load static %}
{% load widget_tweaks %}
{% load humanize %}
{% block title %}D_SHOPPING - TOP{% endblock %}

{% block contents %}

{% include 'include/user_header.html' %}

<main role="main">
  <section class="text-center px-4 py-5">
    <div class="container">
      {% if messages %}
      <div class="row">
        <div class="my-div-style w-100">
          <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}">
              {% endif %}
              {{ message }}
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
      {% endif %}
      <!-- Modal -->
      <div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog" aria-labelledby="confirm-delete-modal-label" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="confirm-delete-modal-label">カートから削除しますか？</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="" method="post">
              {% csrf_token %}
              <div class="modal-body" id="delete-cart-item-name">

              </div>
              <input type="hidden" name="product_id" value="">
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                <button type="submit" name="delete-cart-item" class="btn btn-danger">削除する</button>
              </div>
            </form>
          </div>
        </div>
      </div>

      {% if cart_items %}
      <h2>カートに入れた商品</h2>
      <div class="row">
        <table class="table mt-5 ml-3 border-dark">
          <thead>
          <tr class="text-center">
            <th class="border-bottom border-dark" style="width:10%;">商品画像</th>
            <th class="border-bottom border-dark" style="width:20%;">商品名</th>
            <th class="border-bottom border-dark" style="width:20%;">商品カテゴリ</th>
            <th class="border-bottom border-dark" style="width:15%;">値段</th>
            <th class="border-bottom border-dark" style="width:15%;">個数</th>
            <th class="border-bottom border-dark" style="width:15%;">小計</th>
            <th class="border-bottom border-dark" style="width:10%;"></th>
          </tr>
          </thead>
          <tbody>
            {% for item in cart_items %}
            <form action="" method="post">
              {% csrf_token %}
              <tr class="text-center">
                <td class="align-middle">
                  {% if item.image %}
                  <img class="card-img-top" src="/media/{{ item.image }}">
                  {% else %}
                  <img class="card-img-top" src="{% static '/images/no-image.jpg' %}">
                  {% endif %}
                </td>
                <td class="align-middle item-name">{{ item.name }}</td>
                <td class="align-middle">{{ item.category.name }}</td>
                <td class="align-middle">¥{{ item.price|intcomma }}</td>
                <td class="align-middle">
                  {{ item.qty_form.qty }} 個
                  <button name="update-qty" type="submit" class="change-qty-btn">更新</button>
                </td>
                {{ item.qty_form.qty.errors }}
                {{ item.qty_form.product_id.as_hidden }}
                <td class="align-middle">¥{{ item.subtotal|intcomma }}</td>
                <td class="align-middle" id="btn-parent-{{ forloop.counter }}">
                  <a href="#" class="cart-item-delete-btn" data-toggle="modal" data-target="#confirm-delete-modal">削除</a>
                </td>
              </tr>
            </form>
            {% endfor %}
            <tr class="text-center">
              <td class="border-bottom-0 align-middle"></td>
              <td class="border-bottom-0 align-middle"></td>
              <td class="border-bottom-0 align-middle"></td>
              <td class="border-bottom-0 align-middle"></td>
              <td class="border-bottom-0 align-middle font-weight-bold">合計</td>
              <td class="border-bottom-0 align-middle font-weight-bold">¥{{ total_price|intcomma }}</td>
              <td class="border-bottom-0 align-middle"></td>
            </tr>
          </tbody>
        </table>
        <div class="container d-flex justify-content-center mt-3">
          <p class="mx-5">
            <a class="btn btn-success" href="/" role="button">
              買い物を続ける
            </a>
          </p>
          <form action="{% url 'user_order' %}" method="post">
            {% csrf_token %}
            <p class="mx-5">
              <button type="submit" class="btn btn-primary" name="input-order-info">
                注文手続きへ進む
              </button>
            </p>
          </form>
        </div>
      </div>
      {% else %}
      <h1>カートに商品はありません。</h1>
      {% endif %}
    </div>
  </section>
</main>

{% include 'include/user_footer.html' %}

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/common.js' %}"></script>
<script>
$(document).ready(function() {
  $('.cart-item-delete-btn').click(function(){
    var tr_field = $(this).closest('tr');
    var name = tr_field.find('td.item-name').text()
    var product_id = tr_field.find('input[name="product_id"]').val()

    // モーダルに商品名と、商品idをセット
    $('#delete-cart-item-name').text('商品名：' + name);
    $('#confirm-delete-modal input[name="product_id"]').val(product_id)
  });
});
</script>
{% endblock %}

app/templates/user/user_confirm_order_info.html
{% extends "load_file.html" %}
{% load static %}
{% load widget_tweaks %}
{% load humanize %}
{% block title %}D_shopping - 注文者情報確認画面{% endblock %}

{% block contents %}

{% include 'include/user_header.html' %}

<main role="main">
  <section class="px-4 py-5">
    <div class="mx-auto w-50">
      <h2 class="text-center">注文者情報確認</h2>
      <hr>
      <form action="{% url 'user_order_done' %}" method="post">
        {% csrf_token %}
        <div class="form-content py-4 px-5 bg-light">

          <div class="form-group">
            <label class="font-weight-bold">お名前</label>
            <p class="ml-2">{{ form.name.value }}</p>{{ form.name.as_hidden }}
          </div>
          <div class="form-group">
            <label class="font-weight-bold">フリガナ</label>
            <p class="ml-2">{{ form.name_kana.value }}</p>{{ form.name_kana.as_hidden }}
          </div>
          <div class="form-group">
            <label class="font-weight-bold">メールアドレス</label>
            <p class="ml-2">{{ form.email_address.value }}</p>{{ form.email_address.as_hidden }}
          </div>
          <div class="form-group">
            <label class="font-weight-bold">電話番号</label>
            <p class="ml-2">{{ form.phone_number.value }}</p>{{ form.phone_number.as_hidden }}
          </div>
          <div class="form-group">
            <label class="font-weight-bold">郵便番号</label>
            <p class="ml-2">{{ form.postal_code.value }}</p>{{ form.postal_code.as_hidden }}
          </div>
          <div class="form-group">
            <label class="font-weight-bold">住所</label>
            <p class="ml-2">{{ prefecture.prefecture_name }}{{ form.municipality.value }}{{ form.address.value }}</p>
            <!-- 都道府県id -->
            {{ form.prefecture.as_hidden }}
            <!-- 入力された市区町村 -->
            {{ form.municipality.as_hidden }}
            <!-- 入力された住所 -->
            {{ form.address.as_hidden }}
          </div>
          <div class="container d-flex justify-content-center mt-3">
            <p class="mx-5">
              <input type="button" class="btn btn-secondary" onclick="history.back()" value="戻る">
            </p>
            <p class="mx-5">
              <button type="submit" class="btn btn-primary" name="">
                注文を確定する
              </button>
            </p>
          </div>
        </div>
      </form>
    </div>
  </section>
</main>

{% include 'include/user_footer.html' %}

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/common.js' %}"></script>
{% endblock %}

app/templates/user/user_input_order_info.html
{% extends "load_file.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}D_shopping - 注文者情報入力画面{% endblock %}

{% block contents %}

{% include 'include/user_header.html' %}

<main role="main">
  <section class="px-4 py-5">
    <div class="mx-auto w-50">
      <h2 class="text-center">注文者情報入力</h2>
      <hr>
      <form action="" method="post" name="">
        {% csrf_token %}
        <div class="form-content py-4 px-5 bg-light">
          <div class="form-group">
            <label>お名前 <span class="text-danger">※</span></label>
            {{ form.name|add_class:"form-control"|attr:"placeholder:鈴木 花子" }}
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.name.errors }}
              </div>
            </div>
          </div>
          <div class="form-group">
            <label>フリガナ <span class="text-danger">※</span></label>
            {{ form.name_kana|add_class:"form-control"|attr:"placeholder:スズキ ハナコ" }}
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.name_kana.errors }}
              </div>
            </div>
          </div>
          <div class="form-group">
            <label>メールアドレス <span class="text-danger">※</span></label>
            {{ form.email_address|add_class:"form-control"|attr:"placeholder:aaa@ddd.com" }}
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.email_address.errors }}
              </div>
            </div>
          </div>
          <div class="form-group">
            <label>電話番号 <span class="text-danger">※</span></label>
            {{ form.phone_number|add_class:"form-control"|attr:"placeholder:00011112222" }}
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.phone_number.errors }}
              </div>
            </div>
          </div>
          <div class="form-group">
            <label>郵便番号 <span class="text-danger">※</span></label>
            <div class="d-flex ">
              {{ form.postal_code|add_class:"form-control w-25 mr-2"|attr:"placeholder:0001111" }}
              <button type="button" class="btn btn-sm btn-outline-info" id="search-postal-code">郵便番号検索</button>
            </div>
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.postal_code.errors }}
              </div>
            </div>
          </div>
          <div class="form-group">
            <label>住所 <span class="text-danger">※</span></label>
            {{ form.prefecture|add_class:"form-control"|attr:"placeholder:都道府県" }}
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.prefecture.errors }}
              </div>
            </div>
          </div>
          <div class="form-group">
            {{ form.municipality|add_class:"form-control"|attr:"placeholder:市区町村" }}
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.municipality.errors }}
              </div>
            </div>
          </div>
          <div class="form-group">
            {{ form.address|add_class:"form-control"|attr:"placeholder:番地、建物名、部屋番号を入力してください" }}
            <div class="form-row form-inline">
              <div class="col-9">
                {{ form.address.errors }}
              </div>
            </div>
          </div>
          <div class="container d-flex justify-content-center mt-3">
            <p class="mx-5">
              <a class="btn btn-secondary" href="{% url 'user_cart' %}" role="button">
                戻る
              </a>
            </p>
            <p class="mx-5">
              <button type="submit" class="btn btn-primary" name="confirm-order-info">
                注文者情報確認画面へ
              </button>
            </p>
          </div>
        </div>
      </form>
    </div>
  </section>
</main>

{% include 'include/user_footer.html' %}

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/common.js' %}"></script>
<script>
  $(function(){
    // 郵便番号検索
    $("#search-postal-code").on('click', function () {
      // ajax通信開始
      $.ajax({
        url: "http://zipcloud.ibsnet.co.jp/api/search?zipcode=" + $('#id_postal_code').val(),
        // 現在のドメインと、データ取得先のドメインが異なるため 'jsonp' を指定
        dataType: 'jsonp',
      }).then(
        // 通信成功時の処理
        function (data) {
          if (data.results) {
            // 住所情報を取得
            var result = data.results[0];
            // フォーム入力欄の「都道府県」「市区町村」「住所」に値をセット
            $('#id_prefecture').val(result.prefcode);
            $('#id_municipality').val(result.address2 + result.address3);
          } else {
            alert('住所が見つかりません');
          }
        },
        // 通信失敗時の処理
        function () {
          alert("読み込み失敗");
      });
    });
  });

</script>
{% endblock %}

app/templates/user/user_order_done.html
{% extends "load_file.html" %}
{% load static %}
{% load widget_tweaks %}
{% load humanize %}
{% block title %}D_shopping - 注文完了画面{% endblock %}

{% block contents %}

{% include 'include/user_header.html' %}

<main role="main">
  <section class="px-4 py-5">
    <div class="mx-auto w-50">
      <h2 class="text-center">ご注文完了</h2>
      <hr>
      <div class="px-2">
        <p class="text-center mb-4">{{ name }} 様</p>
        <p class="text-center">ご注文ありがとうございます。</p>
        <p class="text-center">{{ email_address }}に代金支払い情報をお送りいたしましたのでご確認ください。</p>
        <p class="text-center">代金のご入金確認後、商品を発送させていただきます。</p>
      </div>
    </div>
  </section>
</main>

{% include 'include/user_footer.html' %}

{% endblock %}

{% block extra_js %}
<script src="{% static 'js/common.js' %}"></script>
{% endblock %}